# Generated by Django 5.2.4 on 2025-09-04 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_orgmembership'),
        ('core', '0002_remove_domain_is_primary_remove_organization_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization'),
        ),
    ]
