# Generated by Django 5.2.4 on 2025-08-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='location_radius_m',
            field=models.PositiveIntegerField(blank=True, help_text='Meters', null=True),
        ),
        migrations.AddField(
            model_name='shiftbooking',
            name='clock_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftbooking',
            name='clock_in_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftbooking',
            name='clock_in_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftbooking',
            name='clock_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftbooking',
            name='clock_out_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftbooking',
            name='clock_out_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
