# Generated by Django 5.2.4 on 2025-08-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_shift_location_lat_shift_location_lng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='location_lng',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='location_radius_m',
        ),
        migrations.AddField(
            model_name='shift',
            name='allowed_postcode',
            field=models.CharField(blank=True, help_text='e.g. AB12 3CD', max_length=20, null=True),
        ),
    ]
