# Generated by Django 5.2.4 on 2025-08-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_remove_shift_location_lat_remove_shift_location_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftbooking',
            name='clock_in_postcode',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='shiftbooking',
            name='clock_out_postcode',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='allowed_postcode',
            field=models.CharField(blank=True, help_text='e.g. SW1A 1AA (leave blank to skip postcode check)', max_length=16, null=True),
        ),
    ]
