# Generated by Django 5.2.4 on 2025-08-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_shiftbooking_clock_in_postcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftbooking',
            name='clock_out_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shiftbooking',
            name='clock_out_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='shiftbooking',
            name='clock_out_supervisor_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
