# Generated by Django 5.2.4 on 2025-08-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_shiftbooking_clock_out_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftbooking',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
