# Generated by Django 5.2.4 on 2025-08-28 10:16

import django.db.models.deletion
import shifts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_documenttype_compliancedocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('requires_expiry', models.BooleanField(default=True)),
                ('default_validity_days', models.PositiveIntegerField(blank=True, help_text='Optional hint for admins.', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='compliancedocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RenameField(
            model_name='compliancedocument',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AlterUniqueTogether(
            name='compliancedocument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_compliance_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='file',
            field=models.FileField(upload_to=shifts.models.compliance_upload_path),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=16),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='shifts.compliancedoctype'),
        ),
        migrations.RemoveField(
            model_name='compliancedocument',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='compliancedocument',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='compliancedocument',
            name='verified_by',
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
    ]
