# Generated by Django 5.2.4 on 2025-08-29 00:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0008_compliancedoctype_alter_compliancedocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('shift_created', 'Shift created'), ('shift_updated', 'Shift updated'), ('shift_deleted', 'Shift deleted'), ('booking_created', 'Booking created'), ('booking_cancelled', 'Booking cancelled'), ('booking_no_show', 'Marked as no-show'), ('clock_in', 'Clock in'), ('clock_out', 'Clock out'), ('status_override', 'Status override'), ('notes_updated', 'Notes updated')], db_index=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.shiftbooking')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.shift')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_subject_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
