# Generated by Django 5.2.4 on 2025-08-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0009_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftbooking',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
