# Generated by Django 5.2.4 on 2025-08-30 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('shifts', '0011_alter_shift_options_shift_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='organization',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AlterField(
            model_name='shiftbooking',
            name='organization',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
    ]
